name: Generate snake animation

on:
  schedule: 
    - cron: "0 */3 * * *"

  workflow_dispatch:

  push:
    branches:
      - main
      - master
      - test

jobs:
  generate:
    permissions:
      contents: write
      actions: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Depoyu çek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: snake.svg oluştur
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: hamzagedikkaya
          outputs: dist/snake.svg?palette=github-dark

      - name: snake.svg'yi çıkış dalına yükle
        uses: crazy-max/ghaction-github-pages@v3.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
